### ISSUE TITLE
Discovery Page

### ISSUE THREAD

**Issue by besheagl** [besheagl/UNCG-Senior-Project#18]
User story: As a user, I want to be able to discover new discussions, so I can have inspiration for what new shows/books I might want to pick up or talk about.

Create HTML layout.
Use CSS to clean it up.

**Comment by besheagl** [comment]
@ekwells Remind me, is the Discovery Page meant to be sorted by popularity? Or just by the time at which a post was made? I was thinking if it's popularity I could put a placeholder for the number of comments on the post, and if it's time I could put one for the timestamp.

**Comment by ekwells** [comment]
I think its going to be some equation based off the timestamp and the number of comments because going just off of number of comments would have the potential to keep old posts that were popular at the top but they might become irrelevant once they are old but still have many comments. We will have to figure that one out..maybe number of comments within a certain time frame? Thats more along the lines of how a trending page works...
