### ISSUE TITLE
Make the Site Mobile

### ISSUE THREAD

**Issue by besheagl** [besheagl/UNCG-Senior-Project#29]
As a user, I want the site to be mobile so I can access it quickly and easily on my phone.

Learn about HTML 5.
If not done already, make sure the HTML layouts are appropriate for a phone screen. 
Allow the user to "install" the site by bookmarking it on their phone.

**Comment by ekwells** [comment]
Use this meta tag in order to scale the page contents to the mobile screen size:
meta name="viewport" content="width=device-width, initial-scale=1.0"> 
I put it between </head> and <body>
Also where possible dont use px to size things because this is a static size which doesnt scale to different screens. Use % or vw for sizing such as font-size: 5vw; which makes font 5% of the view width

**Comment by ekwells** [comment]
What happened to my copy and pasted meta tag!? >:(
<meta name="viewport" content="width=device-width, initial-scale=1.0">

**Comment by ekwells** [comment]
wow the comment actually read the HTML i copied and didnt display it ok well put a < right before the meta i deleted it so that it would display in the comment
